/**
 * Kanban Board API
 * A simple Kanban board API for task management
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AddPost201Response from '../model/AddPost201Response';
import DeletePost200Response from '../model/DeletePost200Response';
import Get200Response from '../model/Get200Response';

/**
* Default service.
* @module api/DefaultApi
* @version 1.0
*/
export default class DefaultApi {

    /**
    * Constructs a new DefaultApi. 
    * @alias module:api/DefaultApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the addPost operation.
     * @callback module:api/DefaultApi~addPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AddPost201Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add a new task
     * Creates a new task with the given title and description
     * @param {String} title Task title
     * @param {String} description Task description
     * @param {module:api/DefaultApi~addPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AddPost201Response}
     */
    addPost(title, description, callback) {
      let postBody = null;
      // verify the required parameter 'title' is set
      if (title === undefined || title === null) {
        throw new Error("Missing the required parameter 'title' when calling addPost");
      }
      // verify the required parameter 'description' is set
      if (description === undefined || description === null) {
        throw new Error("Missing the required parameter 'description' when calling addPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'title': title,
        'description': description
      };

      let authNames = [];
      let contentTypes = ['application/x-www-form-urlencoded'];
      let accepts = ['application/json'];
      let returnType = AddPost201Response;
      return this.apiClient.callApi(
        '/add', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deletePost operation.
     * @callback module:api/DefaultApi~deletePostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DeletePost200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete a task
     * Removes a task from the database
     * @param {Number} taskId Task ID to delete
     * @param {module:api/DefaultApi~deletePostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DeletePost200Response}
     */
    deletePost(taskId, callback) {
      let postBody = null;
      // verify the required parameter 'taskId' is set
      if (taskId === undefined || taskId === null) {
        throw new Error("Missing the required parameter 'taskId' when calling deletePost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'task_id': taskId
      };

      let authNames = [];
      let contentTypes = ['application/x-www-form-urlencoded'];
      let accepts = ['application/json'];
      let returnType = DeletePost200Response;
      return this.apiClient.callApi(
        '/delete', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the movePost operation.
     * @callback module:api/DefaultApi~movePostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AddPost201Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Move a task to a different status
     * Updates the status of an existing task
     * @param {Number} taskId Task ID to move
     * @param {String} status New status (todo, in_progress, done)
     * @param {module:api/DefaultApi~movePostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AddPost201Response}
     */
    movePost(taskId, status, callback) {
      let postBody = null;
      // verify the required parameter 'taskId' is set
      if (taskId === undefined || taskId === null) {
        throw new Error("Missing the required parameter 'taskId' when calling movePost");
      }
      // verify the required parameter 'status' is set
      if (status === undefined || status === null) {
        throw new Error("Missing the required parameter 'status' when calling movePost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'task_id': taskId,
        'status': status
      };

      let authNames = [];
      let contentTypes = ['application/x-www-form-urlencoded'];
      let accepts = ['application/json'];
      let returnType = AddPost201Response;
      return this.apiClient.callApi(
        '/move', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the rootGet operation.
     * @callback module:api/DefaultApi~rootGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Get200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all tasks
     * Returns a list of all tasks
     * @param {module:api/DefaultApi~rootGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Get200Response}
     */
    rootGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Get200Response;
      return this.apiClient.callApi(
        '/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
