/**
 * Kanban Board API
 * A simple Kanban board API for task management
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Task from './Task';

/**
 * The AddPost201Response model module.
 * @module model/AddPost201Response
 * @version 1.0
 */
class AddPost201Response {
    /**
     * Constructs a new <code>AddPost201Response</code>.
     * @alias module:model/AddPost201Response
     */
    constructor() { 
        
        AddPost201Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AddPost201Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AddPost201Response} obj Optional instance to populate.
     * @return {module:model/AddPost201Response} The populated <code>AddPost201Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddPost201Response();

            if (data.hasOwnProperty('task')) {
                obj['task'] = Task.constructFromObject(data['task']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AddPost201Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AddPost201Response</code>.
     */
    static validateJSON(data) {
        // validate the optional field `task`
        if (data['task']) { // data not null
          Task.validateJSON(data['task']);
        }

        return true;
    }


}



/**
 * @member {module:model/Task} task
 */
AddPost201Response.prototype['task'] = undefined;






export default AddPost201Response;

