/**
 * Kanban Board API
 * A simple Kanban board API for task management
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Task from './Task';

/**
 * The Get200Response model module.
 * @module model/Get200Response
 * @version 1.0
 */
class Get200Response {
    /**
     * Constructs a new <code>Get200Response</code>.
     * @alias module:model/Get200Response
     */
    constructor() { 
        
        Get200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Get200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Get200Response} obj Optional instance to populate.
     * @return {module:model/Get200Response} The populated <code>Get200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Get200Response();

            if (data.hasOwnProperty('tasks')) {
                obj['tasks'] = ApiClient.convertToType(data['tasks'], [Task]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Get200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Get200Response</code>.
     */
    static validateJSON(data) {
        if (data['tasks']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['tasks'])) {
                throw new Error("Expected the field `tasks` to be an array in the JSON data but got " + data['tasks']);
            }
            // validate the optional field `tasks` (array)
            for (const item of data['tasks']) {
                Task.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/Task>} tasks
 */
Get200Response.prototype['tasks'] = undefined;






export default Get200Response;

