/**
 * Kanban Board API
 * A simple Kanban board API for task management
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AddPost201Response from './model/AddPost201Response';
import DeletePost200Response from './model/DeletePost200Response';
import Get200Response from './model/Get200Response';
import Task from './model/Task';
import DefaultApi from './api/DefaultApi';


/**
* A simple Kanban board API for task management.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var KanbanBoardApi = require('index'); // See note below*.
* var xxxSvc = new KanbanBoardApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new KanbanBoardApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new KanbanBoardApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new KanbanBoardApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AddPost201Response model constructor.
     * @property {module:model/AddPost201Response}
     */
    AddPost201Response,

    /**
     * The DeletePost200Response model constructor.
     * @property {module:model/DeletePost200Response}
     */
    DeletePost200Response,

    /**
     * The Get200Response model constructor.
     * @property {module:model/Get200Response}
     */
    Get200Response,

    /**
     * The Task model constructor.
     * @property {module:model/Task}
     */
    Task,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
